# Generated by Django 4.1.6 on 2023-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150)),
                ('barcode', models.CharField(max_length=150)),
                ('warehouse', models.CharField(max_length=150)),
                ('cryer', models.CharField(max_length=150)),
                ('party', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=150)),
                ('number_of_entries', models.IntegerField()),
                ('number_remaining_stack', models.IntegerField()),
                ('input_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('total_income_amount', models.IntegerField()),
                ('delivery_date', models.CharField(max_length=150)),
                ('other_costs', models.CharField(max_length=150)),
                ('comment_amount', models.IntegerField()),
                ('commodity_cost', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scanproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=150)),
                ('barcode', models.CharField(max_length=150)),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
